steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/weather-api', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy weatherapi \
          --image=gcr.io/$_PROJECT_ID/weather-api \
          --platform=managed \
          --region=$_REGION \
          --allow-unauthenticated \
          --vpc-connector=$_VPC_CONNECTOR \
          --set-env-vars=REDISHOST=$$REDISHOST,REDISPORT=$$REDISPORT,GOOGLE_CLOUD_PROJECT=$_PROJECT_ID,ENVIRONMENT=$_ENVIRONMENT

# CORRECT PLACEMENT FOR SECRETS
availableSecrets:
  secretManager:
  - versionName: projects/leafy-ether-456618-q6/secrets/REDISHOST/versions/latest
    env: 'REDISHOST'
  - versionName: projects/leafy-ether-456618-q6/secrets/REDISPORT/versions/latest
    env: 'REDISPORT'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: leafy-ether-456618-q6
  _REGION: europe-west10
  _VPC_CONNECTOR: redis-weather-connector
  _ENVIRONMENT: production
