version: '3.9'

services:
  web:
    build: .
    command: fastapi run main.py --port 80 --reload
    volumes:
      - .:/app
      - /c/Users/einma/AppData/Roaming/gcloud/application_default_credentials.json:/secrets/service-account.json
    ports:
      - "8080:80"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-account.json
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    command: redis-server --bind 0.0.0.0
